<?php

namespace Twake\Channels\Repository;

/**
 * ChannelMemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChannelMemberRepository extends \Twake\Core\Services\DoctrineAdapter\RepositoryAdapter
{
}
