<?php

namespace Twake\Channels\Repository;

/**
 * ChannelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChannelRepository extends \Twake\Core\Services\DoctrineAdapter\RepositoryAdapter
{
}
