<?php

namespace WebsiteApi\CallsBundle\Repository;

/**
 * CallmemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CallMemberRepository extends \Doctrine\ORM\EntityRepository
{
}
