<?php

namespace WebsiteApi\CallsBundle\Repository;

/**
 * CallRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CallRepository extends \Doctrine\ORM\EntityRepository
{
}
