<?php

namespace Twake\Upload\Repository;

/**
 * FileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileRepository extends \Twake\Core\Services\DoctrineAdapter\RepositoryAdapter
{
    public function sumAllFileSize($idTwakeUser)
    {
        $req = $this->createQueryBuilder('F')
            ->select('sum(F.sizes)');
        $req->where('F.owner = \'' . $idTwakeUser . '\'');
        $req = $req->getQuery()->getResult();
        return $req;
    }
}
