<?php

namespace WebsiteApi\MarketBundle\Repository;
use http\Env\Request;

/**
 * DataTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataTokenRepository extends \WebsiteApi\CoreBundle\Services\DoctrineAdapter\RepositoryAdapter
{
    public function removeToken($token){
        $qb = $this->createQueryBuilder('s');
        $qb->delete();
        $qb->where('s.token = :token');
        $qb->setParameter('token', $token);
        $qb->getQuery()->execute();
    }

}