<?php

namespace WebsiteApi\MarketBundle\Repository;
use http\Env\Request;

/**
 * DataTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataTokenRepository extends \Doctrine\ORM\EntityRepository
{

}