<?php

namespace WebsiteApi\MarketBundle\Repository;

/**
 * LinkAppOrgaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkAppOrgaRepository extends \Doctrine\ORM\EntityRepository
{
}