<?php

namespace WebsiteApi\MarketBundle\Repository;

/**
 * LinkAppWorkspaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkAppWorkspaceRepository extends \Doctrine\ORM\EntityRepository
{
}