<?php

namespace WebsiteApi\MarketBundle\Repository;

/**
 * LinkAppUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkAppUserRepository extends \Doctrine\ORM\EntityRepository
{
}