<?php

namespace AdministrationApi\Counter\Repository;

/**
 * CounterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CounterRepository extends \Twake\Core\Services\DoctrineAdapter\RepositoryAdapter
{
}
