<?php

namespace Twake\GlobalSearch\Repository;

/**
 * BlocRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlocRepository extends \Twake\Core\Services\DoctrineAdapter\RepositoryAdapter
{


}
