<?php


namespace Twake\GlobalSearch\Repository;

/**
 * SearchHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SearchHistoryRepository extends \Twake\Core\Services\DoctrineAdapter\RepositoryAdapter
{


}
