<?php


namespace Twake\Drive\Repository;

/**
 * UploadStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UploadStateRepository extends \Twake\Core\Services\DoctrineAdapter\RepositoryAdapter
{

}
