<?php

namespace Twake\Core\Repository;

/**
 * SessionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SessionsRepository extends \Twake\Core\Services\DoctrineAdapter\RepositoryAdapter
{
}
