<?php

namespace Twake\Core\Repository;

/**
 * WebsocketsRouteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebsocketsRouteRepository extends \Twake\Core\Services\DoctrineAdapter\RepositoryAdapter
{
}
