<?php

namespace WebsiteApi\GlobalSearchBundle\Repository;

/**
 * BlocRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlocRepository extends \WebsiteApi\CoreBundle\Services\DoctrineAdapter\RepositoryAdapter
{

//    public function findOneBy(Array $arr)
//    {
//        $res="";
//        var_dump("passage");
//        return $res;
//    }

}
