<?php


namespace WebsiteApi\GlobalSearchBundle\Repository;

/**
 * SearchHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SearchHistoryRepository extends \WebsiteApi\CoreBundle\Services\DoctrineAdapter\RepositoryAdapter
{


}
