<?php

namespace WebsiteApi\GlobalSearchBundle\Repository;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \WebsiteApi\CoreBundle\Services\DoctrineAdapter\RepositoryAdapter
{

    public function findOneBy(Array $arr)
    {
//        $res = parent::findOneBy($arr);
//
//        if ($res) {
//            $res->setIdAsString();
//        }
        $res= "";
//
        return $res;
    }

}