<?php

namespace WebsiteApi\UploadBundle\Repository;

/**
 * FileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileRepository extends \Doctrine\ORM\EntityRepository
{
    public function sumAllFileSize($idTwakeUser){
        $req = $this->createQueryBuilder('F')
            ->select('sum(F.sizes)');
        $req->where('F.owner = \'' . $idTwakeUser .'\'');
        $req = $req->getQuery()->getResult();
        return $req;
    }
}
