version: "3.4"

services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./docker-data/mongo:/data/db

  node:
    image: twaketech/twake-node
    ports:
      - 3000:3000
    environment:
      - DEV=production
      - SEARCH_DRIVER=mongodb
      - DB_DRIVER=mongodb
      - PUBSUB_TYPE=local
    build:
      context: .
      dockerfile: ./docker/twake-node/Dockerfile
      target: development
    volumes:
      - ./docker-data/documents/:/storage/
    depends_on:
      - mongo
    links:
      - mongo