version: "3.4"

services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./docker-data/mongo:/data/db

  plugins:
    image: twaketech/twake-plugins:latest
    
  node:
    image: twaketech/twake-node:latest
    ports:
      - 3000:3000
    environment:
      - DEV=production
      - SEARCH_DRIVER=mongodb
      - DB_DRIVER=mongodb
      - PUBSUB_TYPE=local
      - PLUGINS_SERVER=plugins:3100
    volumes:
      - ./docker-data/documents/:/storage/
    depends_on:
      - mongo
    links:
      - mongo