<?php

namespace WebsiteApi\OrganizationsBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkOrgaParentRepository extends \Doctrine\ORM\EntityRepository
{
}