<?php

namespace WebsiteApi\OrganizationsBundle\Repository;

/**
 * LinkOrgaUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkOrgaUserRepository extends \Doctrine\ORM\EntityRepository
{
	public function getSomeUsers($organization,$type, $offset, $length)
	{
		$qb = $this->createQueryBuilder("l")
			->select('l')
			->where('l.Orga = :organization')
			->andWhere('l.status = :type');
		if($length>0) {
			$qb = $qb->setMaxResults($length);
		}
		$qb = $qb->setFirstResult($offset)
			->setParameter('organization', $organization)
			->setParameter('type', $type);

		return $qb->getQuery()->getResult();
	}
}
