<?php

namespace WebsiteApi\OrganizationsBundle\Repository;

/**
 * OrgaSubscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrgaSubscriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
