@baseURL = http://localhost:3000/api

# @name login
GET {{baseURL}}/auth/login

###

@authToken = {{login.response.body.token}}
GET {{baseURL}}/channels
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name createChannel
POST {{baseURL}}/channels
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "My channel",
  "creator": "111"
}

###

@deleteId = {{createChannel.response.body.id}}

DELETE {{baseURL}}/channels/{{deleteId}}
