@company_id = 0
@workspace_id = 0
@baseURL = http://localhost:3000/api
@channelsURL = {{baseURL}}/channels/companies/{{company_id}}/workspaces/{{workspace_id}}

# @name login
GET {{baseURL}}/auth/login

### List channels

@authToken = {{login.response.body.token}}
GET {{channelsURL}}/channels
Content-Type: application/json
Authorization: Bearer {{authToken}}

### Create a channel

# @name createChannel
POST {{channelsURL}}/channels
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "My channel"
}

### Get a single channel

@getId = {{createChannel.response.body.resource.id}}

GET {{channelsURL}}/channels/{{getId}}


### Delete a channel

@deleteId = {{createChannel.response.body.resource.id}}

DELETE {{channelsURL}}/channels/{{deleteId}}
