<?php

namespace Twake\Market\Repository;

/**
 * ApplicationResourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationResourceRepository extends \Twake\Core\Services\DoctrineAdapter\RepositoryAdapter
{

}