<?php

namespace Twake\Market\Repository;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends \Twake\Core\Services\DoctrineAdapter\RepositoryAdapter
{

}