<?php

namespace Twake\Market\Repository;

/**
 * DataTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataTokenRepository extends \Twake\Core\Services\DoctrineAdapter\RepositoryAdapter
{

}