<?php

namespace WebsiteApi\WorkspacesBundle\Repository;

/**
 * AppPricingInstance
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppPricingInstanceRepository extends \Doctrine\ORM\EntityRepository
{
}
