<?php

namespace WebsiteApi\WorkspacesBundle\Repository;

/**
 * ArchivedGroupPeriod
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArchivedGroupPeriodRepository extends \Doctrine\ORM\EntityRepository
{
}
