<?php

namespace WebsiteApi\WorkspacesBundle\Repository;

/**
 * ClosedGroupPeriod
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClosedGroupPeriodRepository extends \Doctrine\ORM\EntityRepository
{
}
