<?php

namespace WebsiteApi\WorkspacesBundle\Repository;

/**
 * GroupPeriod
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupPeriodRepository extends \Doctrine\ORM\EntityRepository
{
}
