<?php

namespace WebsiteApi\WorkspacesBundle\Repository;

/**
 * GroupPricingInstance
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupPricingInstanceRepository extends \Doctrine\ORM\EntityRepository
{
}
