<?php

namespace WebsiteApi\WorkspacesBundle\Repository;

/**
 * GroupPeriod
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupPeriodRepository extends \WebsiteApi\CoreBundle\Services\DoctrineAdapter\RepositoryAdapter
{
    public function getLastGroupPeriod($group){
        $qb = $this->createQueryBuilder('f')
            ->select('max(f.periodStartedAt)')
            ->where('f.group = :group')
            ->setParameter("group", $group);

        $lastDate = $qb->getQuery()->getResult()[0];


        $qb = $this->createQueryBuilder('f')
            ->select('f')
            ->where('f.group = :group')
            ->andWhere('f.periodStartedAt = :last_date')
            ->setParameter("group", $group)
            ->setParameter("last_date", $lastDate);

        return $qb->getQuery()->getResult()[0];
    }
}
