<?php

namespace WebsiteApi\WorkspacesBundle\Repository;

/**
 * GroupAppRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupAppRepository extends \Doctrine\ORM\EntityRepository
{
}
