<?php

namespace WebsiteApi\WorkspacesBundle\Repository;

/**
 * GroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupRepository extends \WebsiteApi\CoreBundle\Services\DoctrineAdapter\RepositoryAdapter
{

    public function getGroup($group_id){
        $qb = $this->createQueryBuilder('g')
            ->select('g')
            ->where('g.id = :id')
            ->setParameter('id', $group_id)
            ->getQuery();

        return $qb->getQuery()->getResult();
    }
}
