<?php

namespace WebsiteApi\WorkspacesBundle\Repository;

/**
 * GroupManagerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupManagerRepository extends \Doctrine\ORM\EntityRepository
{
}
