<?php

namespace WebsiteApi\WorkspacesBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkWorkspaceParentRepository extends \Doctrine\ORM\EntityRepository
{
}