<?php

namespace WebsiteApi\WorkspacesBundle\Repository;

/**
 * PricingPlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PricingPlanRepository extends \Doctrine\ORM\EntityRepository
{
}
