<?php

namespace WebsiteApi\WorkspacesBundle\Repository;

/**
 * LinkWorkspaceUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkspaceUserRepository extends \Doctrine\ORM\EntityRepository
{
	public function getSomeUsers($workspace,$type, $offset, $length)
	{
		$qb = $this->createQueryBuilder("l")
			->select('l')
			->where('l.Workspace = :workspace')
			->andWhere('l.status = :type');
		if($length>0) {
			$qb = $qb->setMaxResults($length);
		}
		$qb = $qb->setFirstResult($offset)
			->setParameter('workspace', $workspace)
			->setParameter('type', $type);

		return $qb->getQuery()->getResult();
	}
}
