<?php

namespace WebsiteApi\WorkspacesBundle\Repository;

/**
 * WorkspaceAppRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkspaceAppRepository extends \Doctrine\ORM\EntityRepository
{
}
