<?php

namespace WebsiteApi\WorkspacesBundle\Repository;

/**
 * LevelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkspaceLevelRepository extends \Doctrine\ORM\EntityRepository
{

    public function getByLabel($label,$workspace){
        $qb = $this->createQueryBuilder('p')
            ->andWhere('p.label like :label')
            ->andWhere('p.workspace = :workspace')
            ->setParameter('label', '%'.$label.'%')
            ->setParameter('workspace', $workspace)
            ->setMaxResults(10)
            ->getQuery();

        return $qb->execute();
    }
}
