<?php

namespace WebsiteApi\WorkspacesBundle\Repository;

/**
 * LevelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkspaceLevelRepository extends \Doctrine\ORM\EntityRepository
{
}
