<?php

namespace WebsiteApi\WorkspacesBundle\Repository;

/**
 * WorkspaceActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class WorkspaceActivityRepository extends \Doctrine\ORM\EntityRepository
{

}