<?php

namespace WebsiteApi\WorkspacesBundle\Repository;

/**
 * WorkspaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkspaceRepository extends \WebsiteApi\CoreBundle\Services\DoctrineAdapter\RepositoryAdapter
{

    public function findOneBy(array $array)
    {
        if (isset($array["is_deleted"])) {
            unset($array["is_deleted"]);

            $ws = parent::findOneBy($array);
            if (($ws->getis_deleted() && !$array["is_deleted"]) || (!$ws->getis_deleted() && $array["is_deleted"])) {
                return null;
            }
            return $ws;
        }
        return parent::findOneBy($array);
    }

}
