<?php

namespace WebsiteApi\WorkspacesBundle\Repository;

/**
 * WorkspaceStatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class WorkspaceStatsRepository extends \WebsiteApi\CoreBundle\Services\DoctrineAdapter\RepositoryAdapter
{

}