<?php

namespace WebsiteApi\WorkspacesBundle\Repository;

/**
 * WorkspaceSubscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkspaceSubscriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
