<?php

namespace WebsiteApi\WorkspacesBundle\Repository;

/**
 * WorkspaceAppRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkspaceAppRepository extends \WebsiteApi\CoreBundle\Services\DoctrineAdapter\RepositoryAdapter
{
}
