<?php

namespace DevelopersApiV1\Core\Repository;

/**
 * AccessLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccessLogRepository extends \Twake\Core\Services\DoctrineAdapter\RepositoryAdapter
{

}
