<?php

namespace WebsiteApi\CalendarBundle\Repository;

/**
 * CalendarExportTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalendarExportTokenRepository extends \Doctrine\ORM\EntityRepository
{
}