<?php

namespace WebsiteApi\CalendarBundle\Repository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalendarEventRepository extends \Doctrine\ORM\EntityRepository
{

    public function removeAllByCalendar($calendar){
        $qb = $this->createQueryBuilder('e');
        $qb->delete('e');
        $qb->where('e.calendar = :calendar');
        $qb->setParameter('calendar', $calendar);
    }

}