<?php

namespace WebsiteApi\CalendarBundle\Repository;

/**
 * LinkCalendarGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkCalendarGroupRepository extends \Doctrine\ORM\EntityRepository
{
}