<?php

namespace WebsiteApi\CalendarBundle\Repository;

/**
 * LinkCalendarUSerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkCalendarUSerRepository extends \Doctrine\ORM\EntityRepository
{
}