<?php

namespace WebsiteApi\CalendarBundle\Repository;

/**
 * LinkCalendarWorkspaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkCalendarWorkspaceRepository extends \Doctrine\ORM\EntityRepository
{
}