<?php

namespace WebsiteApi\CalendarBundle\Repository;

/**
 * LinkEventUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkEventUserRepository extends \Doctrine\ORM\EntityRepository
{
}