<?php

namespace Twake\Users\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DeviceRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class DeviceRepository extends EntityRepository
{
}
