<?php

namespace Twake\Users\Repository;

/**
 * MailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailRepository extends \Twake\Core\Services\DoctrineAdapter\RepositoryAdapter
{
}
