<?php

namespace Twake\Users\Repository;

use Twake\Users\Entity\Token;

/**
 * TokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TokenRepository extends \Twake\Core\Services\DoctrineAdapter\RepositoryAdapter
{
    public function deleteToken(Token $userToken)
    {
        $qb = $this->createQueryBuilder('s');
        $qb->delete();
        $qb->where('s.id = :id');
        $qb->setParameter('id', $userToken->getId());
        $qb->getQuery()->execute();
    }
}
