<?php

namespace Twake\Users\Repository;

/**
 * UserStatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserStatsRepository extends \Twake\Core\Services\DoctrineAdapter\RepositoryAdapter
{
}
