<?php

namespace Twake\Users\Repository;

/**
 * VerificationNumberMailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VerificationNumberMailRepository extends \Twake\Core\Services\DoctrineAdapter\RepositoryAdapter
{
}
