<?php

namespace WebsiteApi\DriveBundle\Repository;

/**
 * DriveFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DriveFileRepository extends \Doctrine\ORM\EntityRepository
{

	public function sumSize($group, $directory = null)
	{
		$qb = $this->createQueryBuilder('f')
			->select('sum(f.size)')
			->where('f.group = :group')
			->setParameter("group", $group);

		if ($directory == null) {
			$qb = $qb->andWhere('f.parent IS NULL');
		} else {
			$qb = $qb->andWhere('f.parent = :directory')
				->setParameter("directory", $directory);
		}

		return $qb->getQuery()->getSingleScalarResult();
	}

	public function listDirectory($group, $directory = null, $trash = false)
	{

		return $this->findBy(Array(
			"group" => $group,
			"parent" => $directory,
			"isInTrash" => $trash
		), Array("name" => "ASC"));

	}

	public function search($group, $query, $sorts, $offset = 0, $max = 20)
	{
		$qb = $this->createQueryBuilder('f')
			->select('f')
			->where('f.group = :group');

		foreach ($sorts as $key=>$sort){
			$qb = $qb->addOrderBy("f.".$key, $sort);
		}

		//Query search
		if(is_string($query)) {
			$query = str_replace(Array("%", "_"),Array("!%","!_"), $query);
			$qb = $qb->andWhere($qb->expr()->like("f.name", ":query"));
			$qb = $qb->setParameter("query", "%".$query."%");
		}

		$qb = $qb->setParameter("group", $group);

		$qb = $qb->setMaxResults($max);
		$qb = $qb->setFirstResult($offset);

		return $qb->getQuery()->getResult();
	}


}
