<?php

namespace WebsiteApi\CoreBundle\Repository;

/**
 * OrgaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrgaRepository extends \Doctrine\ORM\EntityRepository
{


}
