<?php

namespace WebsiteApi\CoreBundle\Repository;

/**
 * TagsListsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagsListsRepository extends \Doctrine\ORM\EntityRepository
{
}
