<?php

namespace DevelopersApi\UsersBundle\Repository;

/**
 * TokenRepositoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TokenRepository extends \Doctrine\ORM\EntityRepository
{
}
