<?php

namespace Administration\AuthenticationBundle\Repository;

/**
 * AdminUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminUserRepository extends \Doctrine\ORM\EntityRepository
{
}
