<?php

namespace Administration\AuthenticationBundle\Repository;

/**
 * UserTempStatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserTempStatsRepository extends \Doctrine\ORM\EntityRepository
{
}
