<?php

namespace Administration\AuthenticationBundle\Repository;

/**
 * WorkspaceTempStatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkspaceTempStatsRepository extends \Doctrine\ORM\EntityRepository
{
}
