<?php

namespace WebsiteApi\UsersBundle\Repository;

/**
 * VerificationNumberMailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VerificationNumberMailRepository extends \WebsiteApi\CoreBundle\Services\DoctrineAdapter\RepositoryAdapter
{
}
