<?php

namespace Twake\Discussion\Repository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Twake\Core\Services\DoctrineAdapter\RepositoryAdapter
{

}
