<?php

namespace WebsiteApi\CoreBundle\Repository\Entity;

/**
 * LinkOrgaUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkOrgaUserRepository extends \Doctrine\ORM\EntityRepository
{
}
