<?php

namespace Twake\Workspaces\Repository;

/**
 * GroupPricingInstance
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupPricingInstanceRepository extends \Twake\Core\Services\DoctrineAdapter\RepositoryAdapter
{
}
