<?php

namespace Twake\Workspaces\Repository;

/**
 * GroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupRepository extends \Twake\Core\Services\DoctrineAdapter\RepositoryAdapter
{

}
