<?php

namespace Twake\Workspaces\Repository;

/**
 * GroupAppRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupAppRepository extends \Twake\Core\Services\DoctrineAdapter\RepositoryAdapter
{

}
