<?php

namespace Twake\Workspaces\Repository;

/**
 * PricingPlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PricingPlanRepository extends \Twake\Core\Services\DoctrineAdapter\RepositoryAdapter
{
}
