<?php

namespace Twake\Workspaces\Repository;

/**
 * WorkspaceAppRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkspaceAppRepository extends \Twake\Core\Services\DoctrineAdapter\RepositoryAdapter
{
}
