<?php

namespace Twake\Workspaces\Repository;

/**
 * LevelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkspaceLevelRepository extends \Twake\Core\Services\DoctrineAdapter\RepositoryAdapter
{

    public function getByLabel($label, $workspace)
    {
        $qb = $this->createQueryBuilder('p')
            ->andWhere('p.label like :label')
            ->andWhere('p.workspace = :workspace')
            ->setParameter('label', '%' . $label . '%')
            ->setParameter('workspace', $this->queryBuilderUuid($workspace))
            ->setMaxResults(10)
            ->getQuery();

        return $qb->execute();
    }
}
