<?php

namespace Twake\Workspaces\Repository;

/**
 * WorkspaceActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class WorkspaceActivityRepository extends \Twake\Core\Services\DoctrineAdapter\RepositoryAdapter
{

}