<?php

namespace WebsiteApi\ProjectBundle\Repository;

/**
 * LinkBoardWorkspaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkBoardWorkspaceRepository extends \Doctrine\ORM\EntityRepository
{
}