<?php

namespace WebsiteApi\CoreBundle\Repository;

/**
 * WebsocketsRouteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebsocketsRouteRepository extends \WebsiteApi\CoreBundle\Services\DoctrineAdapter\RepositoryAdapter
{
}
