<?php

namespace WebsiteApi\CoreBundle\Repository;

/**
 * ZMQQueueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZMQQueueRepository extends \WebsiteApi\CoreBundle\Services\DoctrineAdapter\RepositoryAdapter
{
}
