<?php

namespace WebsiteApi\UsersBundle\Repository;

use WebsiteApi\UsersBundle\Entity\Token;

/**
 * TokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TokenRepository extends \Doctrine\ORM\EntityRepository
{
    public function deleteToken(Token $userToken){
        $qb = $this->createQueryBuilder('s');
        $qb->delete();
        $qb->where('s.id = :id');
        $qb->setParameter('id', $userToken->getId());
        $qb->getQuery()->execute();
    }
}
