<?php

namespace WebsiteApi\UsersBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllOrderedByName($pageNumber,$nbUserByPage, $filter,&$total){
        $offset = ($pageNumber - 1) * $nbUserByPage;
        $limit = $nbUserByPage;

        $req = $this->createQueryBuilder('U')
            ->select('count(U.id)');
        $req = $this->searchMiddleQueryBuilder($req,$filter);
        $total = $req->getQuery()->getSingleScalarResult();

        $req1 = $this->createQueryBuilder('U');
        $req1 = $this->searchMiddleQueryBuilder($req1,$filter);
        $req1 = $req1->setFirstResult($offset)
            ->setMaxResults($limit)
            ->getQuery()->getResult();
        return $req1;
    }

    public function searchMiddleQueryBuilder($req,$filter){
        if($filter != null) {
            $req = $req->where('U.username LIKE \'%' . $filter . '%\'');// OR U.first_name LIKE \'%' . $filter . '%\' OR U.username LIKE \'%' . $filter . '%\'');
            $req = $req->orWhere('U.lastName LIKE \'%' . $filter . '%\'');
            $req = $req->orWhere('U.firstName LIKE \'%' . $filter . '%\'');
        }
        return $req;
    }

    public function findUsersByFilter($pageNumber,$nbUserByPage,$lastName=null,$firstName=null,$userName=null,$email=null,&$total=null){
        $offset = ($pageNumber - 1) * $nbUserByPage;
        $limit = $nbUserByPage;

        $req = $this->createQueryBuilder('U')
            ->select('count(U.id)');
        $req = $this->middleFindUserQueryBuilder($req,$lastName,$firstName,$userName,$email);
        $total = $req->getQuery()->getSingleScalarResult();

        $req1 = $this->createQueryBuilder('U');
        $req1->where('1=1');
        $req1 = $this->middleFindUserQueryBuilder($req1,$lastName,$firstName,$userName,$email);
        $req1 = $req1->setFirstResult($offset)
            ->setMaxResults($limit)
            ->getQuery()->getResult();
        return $req1;
    }

    public function middleFindUserQueryBuilder($req,$lastName=null,$firstName=null,$userName=null,$email=null){
        if($lastName != null){
            $req=$req->andWhere('U.last_name LIKE \'%' . $lastName.'%\'');
        }
        if($firstName != null){
            $req=$req->andWhere('U.first_name LIKE \'%' . $firstName.'%\'');
        }
        if($userName != null){
            $req=$req->andWhere('U.username LIKE \'%' . $userName.'%\'');
        }
        if($email != null){
            $req=$req->andWhere('U.email LIKE \'%' . $email.'%\'');
        }
        return $req;
    }

 /*   private function searchMiddleQueryBuilder($req,$filters){
        if ($filters != null) {
            if(isset($filters['username'])){
                $req= $req->where('U.username LIKE \'%' . $filters['username'].'%\'');
            }
            if(isset($filters['lastname'])){
                $req= $req->where('U.last_name LIKE \'%' . $filters['lastname'].'%\'');
            }
            if(isset($filters['email'])){
                $req=$req->where('U.email LIKE \'%' . $filters['email'].'%\'');
            }
            if(isset($filters['firstname'])){
                $req= $req->where('U.first_name LIKE \'%' . $filters['firstname'].'%\'');
            }
            if(isset($filters['gender'])){
                $req= $req->where('U.gender LIKE \'' . $filters['gender'].'\'');
            }
            if(isset($filters['enable'])){
                $req=$req->where('U.enable = \'' . $filters['enable'].'\'');
            }
            if(isset($filters['connected'])){
                $req= $req->where('U.connected = \'' . $filters['connected'].'\'');
            }
        }
        return $req;
    }*/

    public function countUsersConnected(){
        $req = $this->createQueryBuilder('U')
            ->select('count(U.id)');
        $req->where('U.connected = 1');
        $req = $req->getQuery()->getSingleScalarResult();
        return $req;
    }

    public function countUsers(){
        $req = $this->createQueryBuilder('U')
            ->select('count(U.id)');
        $req->where('U.enabled = 1');
        $req = $req->getQuery()->getSingleScalarResult();
        return $req;
    }

    public function findByName($name){
        $qb = $this->createQueryBuilder('p')
            ->andWhere('p.username like :name')
            ->setParameter('name', '%'.$name.'%')
            ->setMaxResults(10)
            ->getQuery();

        return $qb->execute();
    }

}
