# Test Stage

FROM node:12.19-alpine as test

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

EXPOSE 3000
EXPOSE 9229

CMD ["npm", "run", "dev:debug"]
