# This Dockerfile is used only for tests since the docker-compose file version does not support build targets
FROM node:12.22.0-alpine

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
