<?php

namespace WebsiteApi\OnlyOfficeBundle\Repository;

/**
 * OnlyofficeFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OnlyofficeFileKeysRepository extends \WebsiteApi\CoreBundle\Services\DoctrineAdapter\RepositoryAdapter
{
}