<?php

namespace WebsiteApi\OnlyOfficeBundle\Repository;

/**
 * OnlyofficeFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OnlyofficeFileRepository extends \Doctrine\ORM\EntityRepository
{
}