<?php

namespace WebsiteApi\DiscussionBundle\Repository;

/**
 * MessageReadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageReadRepository extends \Doctrine\ORM\EntityRepository
{
}
