<?php

namespace WebsiteApi\DiscussionBundle\Repository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StreamRepository extends \Doctrine\ORM\EntityRepository
{
}
