<?php

namespace WebsiteApi\DiscussionBundle\Repository;

/**
 * StreamMemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StreamMemberRepository extends \Doctrine\ORM\EntityRepository
{

	public function removeStream($stream){
        $qb = $this->createQueryBuilder('s');
        $qb->delete();
        $qb->where('s.stream = :stream');
        $qb->setParameter('stream', $stream);
        $qb->getQuery()->execute();
	}

	public function findUnreadMessage($user){
        $qb = $this->createQueryBuilder('u');
        $qb->where('u.unread > 0 AND u.user = :user');
        $qb->setParameter('user', $user);
        $result = $qb->getQuery()->getResult();

        return $result;
    }

}
