<?php

namespace WebsiteApi\DiscussionBundle\Repository;

/**
 * StreamMemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StreamMemberRepository extends \Doctrine\ORM\EntityRepository
{

	public function removeStream($stream){
		$qb = $this->createQueryBuilder();
		$qb->delete('StreamMember', 's');
		$qb->where('s.stream = :stream');
		$qb->setParameter('stream', $stream);
	}

}
