# See https://github.com/docker-library/php/blob/master/7.1/fpm/Dockerfile
FROM php:7.1-fpm-jessie

MAINTAINER Romaric Mourgues <romaric.mourgues@twakeapp.com>

WORKDIR /twake-push-server/

EXPOSE 9000
CMD ["php", "-S", "0.0.0.0:9000"]
