<?php

namespace DevelopersApiV1\CoreBundle\Repository;

/**
 * AccessLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccessLogRepository extends \Doctrine\ORM\EntityRepository
{

}
