name: backend-coverage

on:
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]
    branches: [main, develop, qa, canary]
    paths:
      - "twake/backend/core/**"
      - "twake/backend/node/**"

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"
      - name: unit-test
        run: cd twake && docker-compose -f docker-compose.tests.yml run -e NODE_OPTIONS=--unhandled-rejections=warn node npm run test:unit
      - name: e2e-mongo-test
        run: cd twake && docker-compose -f docker-compose.tests.yml run -e NODE_OPTIONS=--unhandled-rejections=warn -e SEARCH_DRIVER=mongodb -e DB_DRIVER=mongodb -e PUBSUB_TYPE=local node npm run test:e2e
      - name: generate coverage summary
        run: |
          npx istanbul report --dir twake/coverage/merged --include "twake/coverage/**/coverage-final.json" json-summary
          npx istanbul report --dir twake/coverage/merged --include "twake/coverage/**/coverage-final.json" text > twake/coverage/merged/coverage-report.txt
      - name: upload test coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report-${{ github.event.pull_request.number }}
          path: twake/coverage/
      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main
        with:
          coverage-summary-path: twake/coverage/merged/coverage-summary.json
          coverage-path: twake/coverage/merged/coverage-report.txt