name: backend-coverage

on:
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]
    branches: [main, develop, qa, canary]
    paths:
      - "twake/backend/core/**"
      - "twake/backend/node/**"

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"
      - name: unit-test
        run: cd twake && docker-compose -f docker-compose.tests.yml run -e NODE_OPTIONS=--unhandled-rejections=warn node npm run test:unit
      - name: upload test coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report-${{ github.event.pull_request.number }}
          path: twake/coverage/
      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main
        with:
          coverage-summary-path: twake/coverage/coverage-summary.json
          coverage-path: twake/coverage/coverage-report.txt