name: integration-test

on:
  pull_request:
    branches: [main, develop, qa, canary]
    paths:
      - "twake/**"

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: integration-test-build
        run: docker build -t integration-test -f docker/integration-test/Dockerfile .
      - name: integration-test-twake-instance
        run: cd twake && docker-compose -f docker-compose.dev.mongo.yml up &
      - name: integration-test-build
        run: sleep 60 && docker run --network host -e SERVER=http://localhost:8000 integration-test
