<?php

namespace WebsiteApi\PaymentsBundle\Repository;

/**
 * GroupIdentityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BillingUserListRepository extends \Doctrine\ORM\EntityRepository{

    public function removeUser($user){
        $qb = $this->createQueryBuilder('u');
        $qb->delete();
        $qb->where('u.user = :user');
        $qb->setParameter('user', $user);
        $qb->getQuery()->execute();
    }
}
