<?php

namespace WebsiteApi\PaymentsBundle\Repository;

/**
 * BillingUserListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BillingUserListRepository extends \Doctrine\ORM\EntityRepository
{
}
