<?php

namespace WebsiteApi\PaymentsBundle\Repository;

/**
 * GroupIdentityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupIdentityRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByLockDateExpire()
    {
        $qb = $this->createQueryBuilder('u');
        $qb->where('u.lockDate != :null_idf')
            ->andWhere('u.lockDate >= :current_date')
            ->setParameter('null_idf', null)
            ->setParameter('current_date', new \DateTime());

        return $qb->getQuery()
            ->getResult();
    }
}
