<?php

namespace WebsiteApi\PaymentsBundle\Repository;

/**
 * ReceiptRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentsHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
