<?php

namespace WebsiteApi\PaymentsBundle\Repository;

/**
 * GroupIdentityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
