<?php

namespace WebsiteApi\PaymentsBundle\Repository;

/**
 * GroupIdentityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriptionRepository extends \WebsiteApi\CoreBundle\Services\DoctrineAdapter\RepositoryAdapter
{
    public function findLastActiveSub($group)
    {
        $qb = $this->createQueryBuilder('f')
            ->select('max(f.id)')
            ->where('f.group = :group')
            ->setParameter("group", $this->queryBuilderUuid($group));

        $lastId = $qb->getQuery()->getResult()[0];


        $qb = $this->createQueryBuilder('f')
            ->select('f')
            ->where('f.group = :group')
            ->andWhere('f.id = :last_id')
            ->setParameter("group", $this->queryBuilderUuid($group))
            ->setParameter("last_id", $this->queryBuilderUuid($lastId));

        return $qb->getQuery()->getResult()[0];
    }
}
